"""
Django settings for wwwsite project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_j@%ob5n*n&97fh^k5&s%kwo-sp(gk8gkmiyo@8$4kli&d+y@_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOCAL_SETTINGS = True

ALLOWED_HOSTS = []

SITE_URL = 'http://www.spllit.com'
SITE_NAME = "YoWeather"
SITE_SLOGAN = "A simple weather app"

ADMINS = (
    ('Igor Popov', 'igor.popov.ip@gmail.com'),
)

OWNERS = (
    ('Igor Popov', 'igor.popov.ip@gmail.com'),
)

# Email
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "hello@getfuntime.com"
EMAIL_HOST_PASSWORD = "DCsZV{TbZ2J9@P82"
EMAIL_PORT = 587
EMAIL_DEBUG = DEBUG

SERVER_EMAIL = "hello@getfuntime.com"
# Application definition

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'weather',
    'pipeline',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'pipeline.middleware.MinifyHTMLMiddleware',
)

ROOT_URLCONF = 'wwwsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'weather/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'weather.context_processors.site_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'wwwsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'weather_db',
        'USER': 'root',
        'PASSWORD': 'phovietnam',
        'HOST': 'localhost',
        'PORT': ''
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR,'locale'),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)

# Django Pipeline

STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'

PIPELINE = {
    'STYLESHEETS': {
        'styles': {
            'source_filenames': (
                'styles/styles.less',
            ),
            'output_filename': 'css/styles.css',
            'extra_context': {
                'media': 'screen,projection',
            }
        }
    },
    'JAVASCRIPT': {
        'base': {
            'source_filenames': (
                'scripts/third-party/react.js',
                'scripts/third-party/react-dom.js',
                'scripts/third-party/browser.js',
                'scripts/third-party/jquery.js',
            ),
            'output_filename': 'js/jquery.min.js',
        },
        'app': {
            'source_filenames': (
                "scripts/third-party/Chart.bundle.js",
                "scripts/sections/app.jsx",
            ),
            'output_filename': 'js/app.min.js',
        }
    }
}

PIPELINE['CSS_COMPRESSOR'] = 'pipeline.compressors.yuglify.YuglifyCompressor'

PIPELINE['JS_COMPRESSOR'] = 'pipeline.compressors.jsmin.JSMinCompressor'

PIPELINE['COMPILERS'] = (
  'react.utils.pipeline.JSXCompiler',
  'pipeline.compilers.less.LessCompiler',
)

PIPELINE['MIMETYPES'] = (
    (b'text/coffeescript', '.coffee'),
    (b'text/less', '.less'),
    (b'text/javascript', '.js'),
    (b'text/babel', '.jsx'),
    (b'text/x-sass', '.sass'),
    (b'text/x-scss', '.scss')
)

# OpenWeatherMap Keys
API_KEY = '6b96a4fbf0d99b2abffc879cf84003e0'
API_URL = 'http://api.openweathermap.org/data/2.5/forecast'
